<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG_SPECIAL</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DelegateDemo.dll" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="DelegateDemo.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\M-010-CS-Fortgeschritten Linq_Erweiterungsmethoden\LinqLab\Lab13.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SolarSystem">
      <HintPath>..\..\..\M-003-CS-Fortgeschritten Generics\SolarSystem\SolarSystem\bin\Debug\net10.0\SolarSystem.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
